FROM oven/bun AS base

WORKDIR /mnt

COPY . .

RUN bun install

RUN bunx --bun vite build

FROM thistine/simple-http-server AS runner

WORKDIR /mnt

COPY --from=base /mnt/dist ./static

ENTRYPOINT [ "/app/serviceapifrontend" ]

EXPOSE 4000